#spring:
#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 2
#    sentinel:
#      master: master
#      nodes: 127.0.0.1:6379
#    password:

